### PR TITLE
Nebula-netbox support

### PR DESCRIPTION
**Pull request by kimpaller**
This implements:
1. Mapping of nebula-config fields to its equivalent netbox attributes using the template_gen.yaml file.
2. Create class for NetboxDevice and NetboxDevices which abstracts device models on netbox. Currently, access to netbox is read only but may expanded to write as well to unify transactions from nebula -> netbox and vice versa.
3. Add tasks to generate nebula-config from an initialized NetboxDevice or NetboxDevices objects using the template_gen.yaml file as template.

### CODE REVIEW

**Comment by jpineda3** [comment]
Just some inconsistency with fields in quotation marks between existing nebula-config and the generated config from netbox.
Any issue with passing these field values to to functions/methods that access them?

in quotation marks in nebula-config but not from config generated from netbox
jtag-config: jtag_cable_id
jtag-config: jtag_cpu_target_name

not in quotation marks in nebula-config but in quotation marks when generated from netbox
netbox-config: netbox_server_port
pdu-config: outlet
uart-config: baudrate

**Review by jpineda3 — COMMENTED** [review]
Just some inconsistency with fields in quotation marks between existing nebula-config and the generated config from netbox.
Any issue with passing these field values to functions/methods that access them?

in quotation marks in nebula-config but not from config generated from netbox
jtag-config: jtag_cable_id
jtag-config: jtag_cpu_target_name

not in quotation marks in nebula-config but in quotation marks when generated from netbox
netbox-config: netbox_server_port
pdu-config: outlet
uart-config: baudrate

**Review by tfcollins — APPROVED** [review]

**Review by tagoylo — COMMENTED** [review]
Run pre-commit for linting issues.

**Comment by kimpaller** [comment]
> Just some inconsistency with fields in quotation marks between existing nebula-config and the generated config from netbox. Any issue with passing these field values to functions/methods that access them?
> 
> in quotation marks in nebula-config but not from config generated from netbox jtag-config: jtag_cable_id jtag-config: jtag_cpu_target_name
> 
> not in quotation marks in nebula-config but in quotation marks when generated from netbox netbox-config: netbox_server_port pdu-config: outlet uart-config: baudrate

quotation marks so far on some fields does not affect operations. may neglect for now and observe in subsequent tests

**Pull request merged**
